# -*- coding: utf-8 -*-

from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtWidgets import QFileDialog,QApplication,QMainWindow
from send2hass import  change_state
import sys
import time
from datetime import datetime
import img_rc

event_log = [] #操作日志缓存
log = [] #生成日志缓存

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1024, 768)

        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.background = QtWidgets.QLabel(self.centralwidget)
        self.background.setGeometry(QtCore.QRect(10, -50, 1001, 871))
        self.background.setStyleSheet("image: url(:/home/sensorlayout2.png);")
        self.background.setObjectName("background")
        #sensor definition
        self.m047 = QtWidgets.QPushButton(self.centralwidget)
        self.m047.setGeometry(QtCore.QRect(50, 83, 50, 20))
        self.m047.setObjectName("m047")
        self.m047.setCheckable(True)
        self.m048 = QtWidgets.QPushButton(self.centralwidget)
        self.m048.setGeometry(QtCore.QRect(150, 83, 50, 20))
        self.m048.setObjectName("m048")
        self.m048.setCheckable(True)
        self.m046 = QtWidgets.QPushButton(self.centralwidget)
        self.m046.setGeometry(QtCore.QRect(50, 150, 50, 21))
        self.m046.setObjectName("m046")
        self.m046.setCheckable(True)
        self.m045 = QtWidgets.QPushButton(self.centralwidget)
        self.m045.setGeometry(QtCore.QRect(50, 230, 50, 21))
        self.m045.setObjectName("m045")
        self.m045.setCheckable(True)
        self.m044 = QtWidgets.QPushButton(self.centralwidget)
        self.m044.setGeometry(QtCore.QRect(170, 290, 50, 21))
        self.m044.setObjectName("m044")
        self.m044.setCheckable(True)
        self.m050 = QtWidgets.QPushButton(self.centralwidget)
        self.m050.setGeometry(QtCore.QRect(150, 230, 50, 21))
        self.m050.setObjectName("m050")
        self.m050.setCheckable(True)
        self.m049 = QtWidgets.QPushButton(self.centralwidget)
        self.m049.setGeometry(QtCore.QRect(152, 150, 50, 21))
        self.m049.setObjectName("m049")
        self.m049.setCheckable(True)
        self.m044 = QtWidgets.QPushButton(self.centralwidget)
        self.m044.setGeometry(QtCore.QRect(170, 290, 50, 21))
        self.m044.setObjectName("m044")
        self.m044.setCheckable(True)
        self.m043 = QtWidgets.QPushButton(self.centralwidget)
        self.m043.setGeometry(QtCore.QRect(160, 348, 50, 21))
        self.m043.setObjectName("m043")
        self.m043.setCheckable(True)
        self.m042 = QtWidgets.QPushButton(self.centralwidget)
        self.m042.setGeometry(QtCore.QRect(250, 348, 50, 20))
        self.m042.setObjectName("m042")
        self.m042.setCheckable(True)
        self.m027 = QtWidgets.QPushButton(self.centralwidget)
        self.m027.setGeometry(QtCore.QRect(50, 410, 50, 20))
        self.m027.setObjectName("m027")
        self.m027.setCheckable(True)
        self.m028 = QtWidgets.QPushButton(self.centralwidget)
        self.m028.setGeometry(QtCore.QRect(160, 410, 50, 20))
        self.m028.setObjectName("m028")
        self.m028.setCheckable(True)
        self.m029 = QtWidgets.QPushButton(self.centralwidget)
        self.m029.setGeometry(QtCore.QRect(240, 410, 50, 20))
        self.m029.setObjectName("m029")
        self.m029.setCheckable(True)
        self.m037 = QtWidgets.QPushButton(self.centralwidget)
        self.m037.setGeometry(QtCore.QRect(300, 410, 50, 20))
        self.m037.setObjectName("m037")
        self.m037.setCheckable(True)
        self.m030 = QtWidgets.QPushButton(self.centralwidget)
        self.m030.setGeometry(QtCore.QRect(240, 460, 50, 20))
        self.m030.setObjectName("m030")
        self.m030.setCheckable(True)
        self.m038 = QtWidgets.QPushButton(self.centralwidget)
        self.m038.setGeometry(QtCore.QRect(321, 477, 50, 20))
        self.m038.setObjectName("m038")
        self.m038.setCheckable(True)
        self.m031 = QtWidgets.QPushButton(self.centralwidget)
        self.m031.setGeometry(QtCore.QRect(123, 502, 50, 20))
        self.m031.setObjectName("m031")
        self.m031.setCheckable(True)
        self.m036 = QtWidgets.QPushButton(self.centralwidget)
        self.m036.setGeometry(QtCore.QRect(218, 505, 50, 20))
        self.m036.setObjectName("m036")
        self.m036.setCheckable(True)
        self.m035 = QtWidgets.QPushButton(self.centralwidget)
        self.m035.setGeometry(QtCore.QRect(220, 575, 50, 20))
        self.m035.setObjectName("m035")
        self.m035.setCheckable(True)
        self.m032 = QtWidgets.QPushButton(self.centralwidget)
        self.m032.setGeometry(QtCore.QRect(125, 576, 50, 20))
        self.m032.setObjectName("m032")
        self.m032.setCheckable(True)
        self.m033 = QtWidgets.QPushButton(self.centralwidget)
        self.m033.setGeometry(QtCore.QRect(125, 654, 50, 19))
        self.m033.setObjectName("m033")
        self.m033.setCheckable(True)
        self.m034 = QtWidgets.QPushButton(self.centralwidget)
        self.m034.setGeometry(QtCore.QRect(218, 653, 50, 20))
        self.m034.setObjectName("m034")
        self.m034.setCheckable(True)
        self.m039 = QtWidgets.QPushButton(self.centralwidget)
        self.m039.setGeometry(QtCore.QRect(320, 561, 50, 20))
        self.m039.setObjectName("m039")
        self.m039.setCheckable(True)
        self.m040 = QtWidgets.QPushButton(self.centralwidget)
        self.m040.setGeometry(QtCore.QRect(320, 632, 50, 20))
        self.m040.setObjectName("m040")
        self.m040.setCheckable(True)
        self.m041 = QtWidgets.QPushButton(self.centralwidget)
        self.m041.setGeometry(QtCore.QRect(320, 662, 50, 20))
        self.m041.setObjectName("m041")
        self.m041.setCheckable(True)
        self.m004 = QtWidgets.QPushButton(self.centralwidget)
        self.m004.setGeometry(QtCore.QRect(491, 97, 50, 20))
        self.m004.setObjectName("m004")
        self.m004.setCheckable(True)
        self.m005 = QtWidgets.QPushButton(self.centralwidget)
        self.m005.setGeometry(QtCore.QRect(590, 94, 50, 20))
        self.m005.setObjectName("m005")
        self.m005.setCheckable(True)
        self.m003 = QtWidgets.QPushButton(self.centralwidget)
        self.m003.setGeometry(QtCore.QRect(490, 179, 50, 21))
        self.m003.setObjectName("m003")
        self.m003.setCheckable(True)
        self.m006 = QtWidgets.QPushButton(self.centralwidget)
        self.m006.setGeometry(QtCore.QRect(590, 180, 50, 21))
        self.m006.setObjectName("m006")
        self.m006.setCheckable(True)
        self.m010 = QtWidgets.QPushButton(self.centralwidget)
        self.m010.setGeometry(QtCore.QRect(690, 180, 50, 21))
        self.m010.setObjectName("m010")
        self.m010.setCheckable(True)
        self.m011 = QtWidgets.QPushButton(self.centralwidget)
        self.m011.setGeometry(QtCore.QRect(690, 94, 50, 21))
        self.m011.setObjectName("m011")
        self.m011.setCheckable(True)
        self.m012 = QtWidgets.QPushButton(self.centralwidget)
        self.m012.setGeometry(QtCore.QRect(800, 92, 50, 21))
        self.m012.setObjectName("m012")
        self.m012.setCheckable(True)
        self.m013 = QtWidgets.QPushButton(self.centralwidget)
        self.m013.setGeometry(QtCore.QRect(800, 178, 50, 21))
        self.m013.setObjectName("m013")
        self.m013.setCheckable(True)
        self.m014 = QtWidgets.QPushButton(self.centralwidget)
        self.m014.setGeometry(QtCore.QRect(800, 266, 50, 21))
        self.m014.setObjectName("m014")
        self.m014.setCheckable(True)
        self.m015 = QtWidgets.QPushButton(self.centralwidget)
        self.m015.setGeometry(QtCore.QRect(771, 348, 50, 21))
        self.m015.setObjectName("m015")
        self.m015.setCheckable(True)
        self.m016 = QtWidgets.QPushButton(self.centralwidget)
        self.m016.setGeometry(QtCore.QRect(770, 380, 50, 21))
        self.m016.setObjectName("m016")
        self.m016.setCheckable(True)
        self.m017 = QtWidgets.QPushButton(self.centralwidget)
        self.m017.setGeometry(QtCore.QRect(770, 480, 50, 21))
        self.m017.setObjectName("m017")
        self.m017.setCheckable(True)
        self.m018 = QtWidgets.QPushButton(self.centralwidget)
        self.m018.setGeometry(QtCore.QRect(770, 560, 50, 21))
        self.m018.setObjectName("m018")
        self.m018.setCheckable(True)
        self.m002 = QtWidgets.QPushButton(self.centralwidget)
        self.m002.setGeometry(QtCore.QRect(490, 268, 50, 21))
        self.m002.setObjectName("m002")
        self.m002.setCheckable(True)
        self.m001 = QtWidgets.QPushButton(self.centralwidget)
        self.m001.setGeometry(QtCore.QRect(569, 348, 50, 21))
        self.m001.setObjectName("m001")
        self.m001.setCheckable(True)
        self.m019 = QtWidgets.QPushButton(self.centralwidget)
        self.m019.setGeometry(QtCore.QRect(670, 561, 50, 20))
        self.m019.setObjectName("m019")
        self.m019.setCheckable(True)
        self.m009 = QtWidgets.QPushButton(self.centralwidget)
        self.m009.setGeometry(QtCore.QRect(698, 267, 50, 20))
        self.m009.setObjectName("m009")
        self.m009.setCheckable(True)
        self.m007 = QtWidgets.QPushButton(self.centralwidget)
        self.m007.setGeometry(QtCore.QRect(590, 268, 50, 20))
        self.m007.setObjectName("m007")
        self.m007.setCheckable(True)
        self.m008 = QtWidgets.QPushButton(self.centralwidget)
        self.m008.setGeometry(QtCore.QRect(669, 306, 50, 20))
        self.m008.setObjectName("m008")
        self.m008.setCheckable(True)
        self.m023 = QtWidgets.QPushButton(self.centralwidget)
        self.m023.setGeometry(QtCore.QRect(563, 382, 50, 20))
        self.m023.setObjectName("m023")
        self.m023.setCheckable(True)
        self.m021 = QtWidgets.QPushButton(self.centralwidget)
        self.m021.setGeometry(QtCore.QRect(569, 563, 50, 20))
        self.m021.setObjectName("m021")
        self.m021.setCheckable(True)
        self.m022 = QtWidgets.QPushButton(self.centralwidget)
        self.m022.setGeometry(QtCore.QRect(570, 480, 50, 20))
        self.m022.setObjectName("m022")
        self.m022.setCheckable(True)
        self.m025 = QtWidgets.QPushButton(self.centralwidget)
        self.m025.setGeometry(QtCore.QRect(480, 666, 50, 20))
        self.m025.setObjectName("m025")
        self.m025.setCheckable(True)
        self.m024 = QtWidgets.QPushButton(self.centralwidget)
        self.m024.setGeometry(QtCore.QRect(561, 667, 50, 20))
        self.m024.setObjectName("m024")
        self.m024.setCheckable(True)
        self.m026 = QtWidgets.QPushButton(self.centralwidget)
        self.m026.setGeometry(QtCore.QRect(481, 584, 50, 20))
        self.m026.setObjectName("m026")
        self.m026.setCheckable(True)
        self.m051 = QtWidgets.QPushButton(self.centralwidget)
        self.m051.setGeometry(QtCore.QRect(770, 654, 50, 20))
        self.m051.setObjectName("m051")
        self.m051.setCheckable(True)
        self.d001 = QtWidgets.QPushButton(self.centralwidget)
        self.d001.setGeometry(QtCore.QRect(540, 710, 50, 20))
        self.d001.setObjectName("d001")
        self.d001.setCheckable(True)
        self.d002 = QtWidgets.QPushButton(self.centralwidget)
        self.d002.setGeometry(QtCore.QRect(750, 42, 50, 20))
        self.d002.setObjectName("d002")
        self.d002.setCheckable(True)
        self.d009 = QtWidgets.QPushButton(self.centralwidget)
        self.d009.setGeometry(QtCore.QRect(700, 410, 50, 20))
        self.d009.setObjectName("d009")
        self.d009.setCheckable(True)
        self.d008 = QtWidgets.QPushButton(self.centralwidget)
        self.d008.setGeometry(QtCore.QRect(700, 384, 50, 20))
        self.d008.setObjectName("d008")
        self.d008.setCheckable(True)
        self.d003 = QtWidgets.QPushButton(self.centralwidget)
        self.d003.setGeometry(QtCore.QRect(230, 442, 50, 20))
        self.d003.setObjectName("d003")
        self.d003.setCheckable(True)
        self.d004 = QtWidgets.QPushButton(self.centralwidget)
        self.d004.setGeometry(QtCore.QRect(170, 310, 50, 20))
        self.d004.setObjectName("d004")
        self.d004.setCheckable(True)
        self.d006 = QtWidgets.QPushButton(self.centralwidget)
        self.d006.setGeometry(QtCore.QRect(332, 648, 50, 20))
        self.d006.setObjectName("d006")
        self.d006.setCheckable(True)
        self.d011 = QtWidgets.QPushButton(self.centralwidget)
        self.d011.setGeometry(QtCore.QRect(820, 653, 50, 20))
        self.d011.setObjectName("d011")
        self.d011.setCheckable(True)
        self.d051 = QtWidgets.QPushButton(self.centralwidget)
        self.d051.setGeometry(QtCore.QRect(770, 656, 50, 20))
        self.d051.setObjectName("d051")
        self.d051.setCheckable(True)
        self.m020 = QtWidgets.QPushButton(self.centralwidget)
        self.m020.setGeometry(QtCore.QRect(662, 635, 50, 20))
        self.m020.setObjectName("m020")
        self.m020.setCheckable(True)
        self.e002 = QtWidgets.QPushButton(self.centralwidget)
        self.e002.setGeometry(QtCore.QRect(229, 247, 50, 20))
        self.e002.setObjectName("e002")
        self.e002.setCheckable(True)
        self.l002 = QtWidgets.QPushButton(self.centralwidget)
        self.l002.setGeometry(QtCore.QRect(376, 279, 50, 25))
        self.l002.setObjectName("l002")
        self.l002.setCheckable(True)
        self.l001 = QtWidgets.QPushButton(self.centralwidget)
        self.l001.setGeometry(QtCore.QRect(40, 280, 50, 25))
        self.l001.setCheckable(True)
        self.l001.setObjectName("l001")
        self.e001 = QtWidgets.QPushButton(self.centralwidget)
        self.e001.setGeometry(QtCore.QRect(730, 108, 50, 20))
        self.e001.setObjectName("e001")
        self.e001.setCheckable(True)
        self.l011 = QtWidgets.QPushButton(self.centralwidget)
        self.l011.setGeometry(QtCore.QRect(660, 653, 50, 25))
        self.l011.setCheckable(True)
        self.l011.setObjectName("l011")
        self.l009 = QtWidgets.QPushButton(self.centralwidget)
        self.l009.setGeometry(QtCore.QRect(514, 641, 50, 25))
        self.l009.setObjectName("l009")
        self.l009.setCheckable(True)
        self.l006 = QtWidgets.QPushButton(self.centralwidget)
        self.l006.setGeometry(QtCore.QRect(321, 583, 50, 25))
        self.l006.setObjectName("l006")
        self.l006.setCheckable(True)
        self.f001 = QtWidgets.QPushButton(self.centralwidget)
        self.f001.setGeometry(QtCore.QRect(380, 580, 50, 25))
        self.f001.setObjectName("f001")
        self.f001.setCheckable(True)
        self.f002 = QtWidgets.QPushButton(self.centralwidget)
        self.f002.setGeometry(QtCore.QRect(374, 678, 50, 25))
        self.f002.setObjectName("f002")
        self.f002.setCheckable(True)
        self.l007 = QtWidgets.QPushButton(self.centralwidget)
        self.l007.setGeometry(QtCore.QRect(320, 684, 50, 25))
        self.l007.setObjectName("l007")
        self.l007.setCheckable(True)
        self.l004 = QtWidgets.QPushButton(self.centralwidget)
        self.l004.setGeometry(QtCore.QRect(110, 679, 50, 25))
        self.l004.setCheckable(True)
        self.l004.setObjectName("l004")
        self.l005 = QtWidgets.QPushButton(self.centralwidget)
        self.l005.setGeometry(QtCore.QRect(391, 464, 50, 25))
        self.l005.setObjectName("l005")
        self.l005.setCheckable(True)
        self.i008 = QtWidgets.QPushButton(self.centralwidget)
        self.i008.setGeometry(QtCore.QRect(680, 209, 50, 20))
        self.i008.setObjectName("i008")
        self.i008.setCheckable(True)
        self.i009 = QtWidgets.QPushButton(self.centralwidget)
        self.i009.setGeometry(QtCore.QRect(680, 230, 50, 20))
        self.i009.setObjectName("i009")
        self.i009.setCheckable(True)
        self.l003 = QtWidgets.QPushButton(self.centralwidget)
        self.l003.setGeometry(QtCore.QRect(101, 399, 50, 25))
        self.l003.setObjectName("l003")
        self.l003.setCheckable(True)
        self.d005 = QtWidgets.QPushButton(self.centralwidget)
        self.d005.setGeometry(QtCore.QRect(307, 437, 50, 20))
        self.d005.setObjectName("d005")
        self.d005.setCheckable(True)
        self.i011 = QtWidgets.QPushButton(self.centralwidget)
        self.i011.setGeometry(QtCore.QRect(470, 324, 50, 20))
        self.i011.setObjectName("i011")
        self.i011.setCheckable(True)
        self.i012 = QtWidgets.QPushButton(self.centralwidget)
        self.i012.setGeometry(QtCore.QRect(488, 339, 50, 20))
        self.i012.setObjectName("i012")
        self.i012.setCheckable(True)
        self.r002 = QtWidgets.QPushButton(self.centralwidget)
        self.r002.setGeometry(QtCore.QRect(469, 251, 50, 20))
        self.r002.setObjectName("r002")
        self.r002.setCheckable(True)
        self.l010 = QtWidgets.QPushButton(self.centralwidget)
        self.l010.setGeometry(QtCore.QRect(766, 457, 50, 25))
        self.l010.setObjectName("l010")
        self.l010.setCheckable(True)
        self.d003 = QtWidgets.QPushButton(self.centralwidget)
        self.d003.setGeometry(QtCore.QRect(490, 308, 50, 20))
        self.d003.setObjectName("d003")
        self.d003.setCheckable(True)
        self.l008 = QtWidgets.QPushButton(self.centralwidget)
        self.l008.setGeometry(QtCore.QRect(624, 128, 100, 40))
        self.l008.setCheckable(True)
        self.l008.setObjectName("l008")
        self.d012 = QtWidgets.QPushButton(self.centralwidget)
        self.d012.setGeometry(QtCore.QRect(620, 404, 50, 20))
        self.d012.setObjectName("d012")
        self.d012.setCheckable(True)
        self.d016 = QtWidgets.QPushButton(self.centralwidget)
        self.d016.setGeometry(QtCore.QRect(841, 392, 50, 30))
        self.d016.setObjectName("d016")
        self.d016.setCheckable(True)
        self.d007 = QtWidgets.QPushButton(self.centralwidget)
        self.d007.setGeometry(QtCore.QRect(841, 482, 50, 30))
        self.d007.setObjectName("d007")
        self.d007.setCheckable(True)
        self.d014 = QtWidgets.QPushButton(self.centralwidget)
        self.d014.setGeometry(QtCore.QRect(841, 525, 50, 30))
        self.d014.setObjectName("d014")
        self.d014.setCheckable(True)
        self.d015 = QtWidgets.QPushButton(self.centralwidget)
        self.d015.setGeometry(QtCore.QRect(841, 560, 50, 30))
        self.d015.setObjectName("d015")
        self.d015.setCheckable(True)
        self.d010 = QtWidgets.QPushButton(self.centralwidget)
        self.d010.setGeometry(QtCore.QRect(700, 458, 50, 20))
        self.d010.setObjectName("d010")
        self.d010.setCheckable(True)
        self.r001 = QtWidgets.QPushButton(self.centralwidget)
        self.r001.setGeometry(QtCore.QRect(692, 511, 50, 20))
        self.r001.setObjectName("r001")
        self.r001.setCheckable(True)
        

        #t label
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(190, 180, 50, 20))
        self.label_4.setObjectName("label_4")       
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(170, 530, 50, 20))
        self.label_3.setObjectName("label_3")        
        self.label_1 = QtWidgets.QLabel(self.centralwidget)
        self.label_1.setGeometry(QtCore.QRect(640, 210, 50, 20))
        self.label_1.setObjectName("label_1")        
        self.label_5 = QtWidgets.QLabel(self.centralwidget)
        self.label_5.setGeometry(QtCore.QRect(270, 290, 50, 20))
        self.label_5.setObjectName("label_5")        
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(820, 510, 50, 20))
        self.label_2.setObjectName("label_2") 
        
        #t button
        self.pushButton_t004 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_t004.setGeometry(QtCore.QRect(152, 166, 50, 20))
        self.pushButton_t004.setStyleSheet("background-color: rgb(255, 255, 0);")
        self.pushButton_t004.setObjectName("pushButton_t004")
        self.pushButton_t003 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_t003.setGeometry(QtCore.QRect(122, 517, 50, 20))
        self.pushButton_t003.setStyleSheet("background-color: rgb(255, 255, 0);")
        self.pushButton_t003.setObjectName("pushButton_t003")
        self.pushButton_t005 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_t005.setGeometry(QtCore.QRect(229, 277, 50, 20))
        self.pushButton_t005.setStyleSheet("background-color: rgb(255, 255, 0);")
        self.pushButton_t005.setObjectName("pushButton_t005")
        self.pushButton_t002 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_t002.setGeometry(QtCore.QRect(771, 495, 50, 20))
        self.pushButton_t002.setStyleSheet("background-color: rgb(255, 255, 0);")
        self.pushButton_t002.setObjectName("pushButton_t002")
        self.pushButton_t001 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_t001.setGeometry(QtCore.QRect(590, 196, 50, 20))
        self.pushButton_t001.setStyleSheet("background-color: rgb(255, 255, 0);")
        self.pushButton_t001.setObjectName("pushButton_t001")


        self.dateEdit = QtWidgets.QDateEdit(self.centralwidget)
        self.dateEdit.setGeometry(QtCore.QRect(890, 220, 123, 26))
        self.dateEdit.setObjectName("dateEdit")
        self.dateEdit.setDisplayFormat("yyyy-MM-dd")
        self.dateEdit.setDate(QtCore.QDate.currentDate())

        self.timeEdit = QtWidgets.QTimeEdit(self.centralwidget)
        self.timeEdit.setGeometry(QtCore.QRect(890, 260, 123, 26))
        self.timeEdit.setObjectName("timeEdit")
        self.timeEdit.setDisplayFormat("HH:mm:ss")
        self.timeEdit.setTime(QtCore.QTime.currentTime())

        self.toolButton = QtWidgets.QToolButton(self.centralwidget)
        self.toolButton.setGeometry(QtCore.QRect(900, 70, 91, 32))
        self.toolButton.setObjectName("toolButton")
        
        self.toolButton_2 = QtWidgets.QToolButton(self.centralwidget)
        self.toolButton_2.setGeometry(QtCore.QRect(900, 40, 91, 32))
        self.toolButton_2.setObjectName("toolButton_2")

        self.logButton = QtWidgets.QToolButton(self.centralwidget)
        self.logButton.setGeometry(QtCore.QRect(900, 180, 91, 32))
        self.logButton.setObjectName("logButton")
        self.logButton.setCheckable(True)

        self.Slider_4 = QtWidgets.QSlider(self.centralwidget)
        self.Slider_4.setObjectName("T004")
        self.Slider_4.setGeometry(QtCore.QRect(150, 190, 50, 20))
        self.Slider_4.setOrientation(QtCore.Qt.Horizontal)
        self.Slider_4.setValue(20)
        self.Slider_4.setMaximum(40)
        self.Slider_4.setMinimum(0)


        self.Slider_2 = QtWidgets.QSlider(self.centralwidget)
        self.Slider_2.setObjectName("T002")
        self.Slider_2.setGeometry(QtCore.QRect(770, 520, 50, 20))
        self.Slider_2.setOrientation(QtCore.Qt.Horizontal)
        self.Slider_2.setValue(20)
        self.Slider_2.setMaximum(40)
        self.Slider_2.setMinimum(0)


        self.Slider_3 = QtWidgets.QSlider(self.centralwidget)
        self.Slider_3.setObjectName("T003")
        self.Slider_3.setGeometry(QtCore.QRect(120, 540, 50, 20))
        self.Slider_3.setOrientation(QtCore.Qt.Horizontal)
        self.Slider_3.setValue(20)
        self.Slider_3.setMaximum(40)
        self.Slider_3.setMinimum(0)

        self.Slider_5 = QtWidgets.QSlider(self.centralwidget)
        self.Slider_5.setObjectName("T005")
        self.Slider_5.setGeometry(QtCore.QRect(230, 300, 50, 20))
        self.Slider_5.setOrientation(QtCore.Qt.Horizontal)
        self.Slider_5.setValue(20)
        self.Slider_5.setMaximum(40)
        self.Slider_5.setMinimum(0)

        self.Slider_1 = QtWidgets.QSlider(self.centralwidget)
        self.Slider_1.setObjectName("T001")
        self.Slider_1.setGeometry(QtCore.QRect(590, 220, 50, 20))
        self.Slider_1.setOrientation(QtCore.Qt.Horizontal)
        self.Slider_1.setValue(20)
        self.Slider_1.setMaximum(40)
        self.Slider_1.setMinimum(0)

        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.retranslateUi(MainWindow)
        #button click function
        self.m047.clicked.connect(lambda:self.lightsclick(self.m047))
        self.m048.clicked.connect(lambda:self.lightsclick(self.m048))
        self.m046.clicked.connect(lambda:self.lightsclick(self.m046))
        self.m045.clicked.connect(lambda:self.lightsclick(self.m045))
        self.m044.clicked.connect(lambda:self.lightsclick(self.m044))
        self.m050.clicked.connect(lambda:self.lightsclick(self.m050))
        self.m049.clicked.connect(lambda:self.lightsclick(self.m049))
        self.m044.clicked.connect(lambda:self.lightsclick(self.m044))
        self.m043.clicked.connect(lambda:self.lightsclick(self.m043))
        self.m042.clicked.connect(lambda:self.lightsclick(self.m042))
        self.m027.clicked.connect(lambda:self.lightsclick(self.m027))
        self.m028.clicked.connect(lambda:self.lightsclick(self.m028))
        self.m029.clicked.connect(lambda:self.lightsclick(self.m029))
        self.m037.clicked.connect(lambda:self.lightsclick(self.m037))
        self.m030.clicked.connect(lambda:self.lightsclick(self.m030))
        self.m038.clicked.connect(lambda:self.lightsclick(self.m038))
        self.m031.clicked.connect(lambda:self.lightsclick(self.m031))
        self.m036.clicked.connect(lambda:self.lightsclick(self.m036))
        self.m035.clicked.connect(lambda:self.lightsclick(self.m035))
        self.m032.clicked.connect(lambda:self.lightsclick(self.m032))
        self.m033.clicked.connect(lambda:self.lightsclick(self.m033))
        self.m034.clicked.connect(lambda:self.lightsclick(self.m034))
        self.m039.clicked.connect(lambda:self.lightsclick(self.m039))
        self.m040.clicked.connect(lambda:self.lightsclick(self.m040))
        self.m041.clicked.connect(lambda:self.lightsclick(self.m041))
        self.m004.clicked.connect(lambda:self.lightsclick(self.m004))
        self.m005.clicked.connect(lambda:self.lightsclick(self.m005))
        self.m003.clicked.connect(lambda:self.lightsclick(self.m003))
        self.m006.clicked.connect(lambda:self.lightsclick(self.m006))
        self.m010.clicked.connect(lambda:self.lightsclick(self.m010))
        self.m011.clicked.connect(lambda:self.lightsclick(self.m011))
        self.m012.clicked.connect(lambda:self.lightsclick(self.m012))
        self.m013.clicked.connect(lambda:self.lightsclick(self.m013))
        self.m014.clicked.connect(lambda:self.lightsclick(self.m014))
        self.m015.clicked.connect(lambda:self.lightsclick(self.m015))
        self.m016.clicked.connect(lambda:self.lightsclick(self.m016))
        self.m017.clicked.connect(lambda:self.lightsclick(self.m017))
        self.m018.clicked.connect(lambda:self.lightsclick(self.m018))
        self.m002.clicked.connect(lambda:self.lightsclick(self.m002))
        self.m001.clicked.connect(lambda:self.lightsclick(self.m001))
        self.m019.clicked.connect(lambda:self.lightsclick(self.m019))
        self.m009.clicked.connect(lambda:self.lightsclick(self.m009))
        self.m007.clicked.connect(lambda:self.lightsclick(self.m007))
        self.m008.clicked.connect(lambda:self.lightsclick(self.m008))
        self.m023.clicked.connect(lambda:self.lightsclick(self.m023))
        self.m021.clicked.connect(lambda:self.lightsclick(self.m021))
        self.m022.clicked.connect(lambda:self.lightsclick(self.m022))
        self.m025.clicked.connect(lambda:self.lightsclick(self.m025))
        self.m024.clicked.connect(lambda:self.lightsclick(self.m024))
        self.m026.clicked.connect(lambda:self.lightsclick(self.m026))
        self.m051.clicked.connect(lambda:self.lightsclick(self.m051))
        self.d001.clicked.connect(lambda:self.lightsclick(self.d001))
        self.d002.clicked.connect(lambda:self.lightsclick(self.d002))
        self.d009.clicked.connect(lambda:self.lightsclick(self.d009))
        self.d008.clicked.connect(lambda:self.lightsclick(self.d008))
        self.d003.clicked.connect(lambda:self.lightsclick(self.d003))
        self.d004.clicked.connect(lambda:self.lightsclick(self.d004))
        self.d006.clicked.connect(lambda:self.lightsclick(self.d006))
        self.d011.clicked.connect(lambda:self.lightsclick(self.d011))
        self.d051.clicked.connect(lambda:self.lightsclick(self.d051))
        self.m020.clicked.connect(lambda:self.lightsclick(self.m020))
        self.e002.clicked.connect(lambda:self.lightsclick(self.e002))
        self.l002.clicked.connect(lambda:self.lightsclick(self.l002))
        self.l001.clicked.connect(lambda:self.lightsclick(self.l001))
        self.e001.clicked.connect(lambda:self.lightsclick(self.e001))
        self.l011.clicked.connect(lambda:self.lightsclick(self.l011))
        self.l009.clicked.connect(lambda:self.lightsclick(self.l009))
        self.l006.clicked.connect(lambda:self.lightsclick(self.l006))
        self.f001.clicked.connect(lambda:self.lightsclick(self.f001))
        self.f002.clicked.connect(lambda:self.lightsclick(self.f002))
        self.l007.clicked.connect(lambda:self.lightsclick(self.l007))
        self.l004.clicked.connect(lambda:self.lightsclick(self.l004))
        self.l005.clicked.connect(lambda:self.lightsclick(self.l005))
        self.i008.clicked.connect(lambda:self.lightsclick(self.i008))
        self.i009.clicked.connect(lambda:self.lightsclick(self.i009))
        self.l003.clicked.connect(lambda:self.lightsclick(self.l003))
        self.d005.clicked.connect(lambda:self.lightsclick(self.d005))
        self.i011.clicked.connect(lambda:self.lightsclick(self.i011))
        self.i012.clicked.connect(lambda:self.lightsclick(self.i012))
        self.r002.clicked.connect(lambda:self.lightsclick(self.r002))
        self.l010.clicked.connect(lambda:self.lightsclick(self.l010))
        self.d003.clicked.connect(lambda:self.lightsclick(self.d003))
        self.l008.clicked.connect(lambda:self.lightsclick(self.l008))
        self.d012.clicked.connect(lambda:self.lightsclick(self.d012))
        self.d016.clicked.connect(lambda:self.lightsclick(self.d016))
        self.d007.clicked.connect(lambda:self.lightsclick(self.d007))
        self.d014.clicked.connect(lambda:self.lightsclick(self.d014))
        self.d015.clicked.connect(lambda:self.lightsclick(self.d015))
        self.d010.clicked.connect(lambda:self.lightsclick(self.d010))
        self.r001.clicked.connect(lambda:self.lightsclick(self.r001))
        
        self.toolButton.clicked.connect(self.open_f)
        self.toolButton_2.clicked.connect(self.save_f)
        self.logButton.clicked.connect(self.logGenerator)


        self.Slider_1.valueChanged.connect(lambda:self.changeTemp(self.Slider_1, self.label_1, self.pushButton_t001))
        self.Slider_1.sliderReleased.connect(lambda:self.temperatureChange(self.Slider_1))
        self.Slider_2.valueChanged.connect(lambda:self.changeTemp(self.Slider_2, self.label_2, self.pushButton_t002))
        self.Slider_2.sliderReleased.connect(lambda:self.temperatureChange(self.Slider_2))
        self.Slider_3.valueChanged.connect(lambda:self.changeTemp(self.Slider_3, self.label_3, self.pushButton_t003))
        self.Slider_3.sliderReleased.connect(lambda:self.temperatureChange(self.Slider_3))
        self.Slider_4.valueChanged.connect(lambda:self.changeTemp(self.Slider_4, self.label_4, self.pushButton_t004))
        self.Slider_4.sliderReleased.connect(lambda:self.temperatureChange(self.Slider_4))
        self.Slider_5.valueChanged.connect(lambda:self.changeTemp(self.Slider_5, self.label_5, self.pushButton_t005))
        self.Slider_5.sliderReleased.connect(lambda:self.temperatureChange(self.Slider_5))

        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def changeTemp(self, slider, temp_label, temp_button):
        value = slider.value()
        if value < 16:
            temp_button.setStyleSheet("background-color: rgb(65, 105 ,225);")
        elif value < 26:
            temp_button.setStyleSheet("background-color: rgb(255, 255, 0);")
        else:
            temp_button.setStyleSheet("background-color: rgb(255, 69, 0);")         
        temp_label.setText(str(value))

    
    def open_f(self):
        fileName1, filetype = QFileDialog.getOpenFileName(self, "选取文件", "./", "All Files (*);;Text Files (*.txt)")  #设置文件扩展名过滤,注意用双分号间隔
        #print(fileName1,filetype)
        f = open(fileName1,'r')
        old_time = datetime.strptime(' 2100-01-01 00:00:0.0', " %Y-%m-%d %H:%M:%S.%f")
        for line in f:
            if len(line) < 5  :
                f.close()
                print('FINISHED!!!')
                break
            
            print(line)
            tmp = line.split('\t')

            if tmp[1][0] == 'T':
                slider = self.findChild(QtWidgets.QSlider,tmp[1])
                slider.setValue(int(tmp[2]))
                QApplication.processEvents()
            else:
                button = self.findChild(QtWidgets.QPushButton,tmp[1].lower())
                button.click()
                QApplication.processEvents()

            new_time = datetime.strptime(tmp[0], " %Y-%m-%d %H:%M:%S.%f")
            if new_time >= old_time:
                t = new_time - old_time
                t = t.seconds
            else:
                t = 0
            old_time = new_time       
            time.sleep(t)

    def save_f(self):
        fileName2, filetype = QFileDialog.getSaveFileName(self, "文件保存", "./", "All Files (*);;Text Files (*.txt)")
        f = open(fileName2,'w')
        f.writelines(event_log)
        f.close()



    def lightsclick(self,button):
        lname = button.objectName()
        entity_id = 'light.'+lname
        if button.isChecked(): #点击与check改变同时发生
            new_state='on'    
        else:
            new_state='off'    

        if self.logButton.isChecked():
            event_time = self.dateEdit.date().toString(" yyyy-MM-dd") + self.timeEdit.time().toString(" HH:mm:ss")
            log_line = event_time+'\t' +lname.upper()+'\t'+new_state.upper()+'\n'
            log.append(log_line)    
        else:     
            event_time = time.strftime(" %Y-%m-%d %H:%M:%S", time.localtime())
            change_state(entity_id, new_state)
            log_line = event_time+'\t' +lname.upper()+'\t'+new_state.upper()+'\n'
            event_log.append(log_line)   

        

    def temperatureChange(self,slider):
        tname=slider.objectName()
        entity_id = 'sensor.'+tname
        new_state = str(slider.value())
        
        if self.logButton.isChecked():
            event_time = self.dateEdit.date().toString(" yyyy-MM-dd") + self.timeEdit.time().toString(" HH:mm:ss")
            log_line = event_time+'\t' +tname+'\t'+new_state+'\n'
            log.append(log_line)   
        else:    
            event_time = time.strftime(" %Y-%m-%d %H:%M:%S", time.localtime())
            change_state(entity_id, new_state)
            log_line = event_time+'\t' +tname+'\t'+new_state+'\n'
            event_log.append(log_line)   
                
    def logGenerator(self):
        if self.logButton.isChecked():
            self.logButton.setText("完成")
        else:
            self.logButton.setText("生成日志")
            fileName2, filetype = QFileDialog.getSaveFileName(self, "文件保存", "./", "All Files (*);;Text Files (*.txt)")
            f = open(fileName2,'w')
            f.writelines(log)
            f.close()
    

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle("smart home UI")
        self.m047.setText("M047")
        self.m048.setText("M048")
        self.m046.setText("M046")
        self.m045.setText("M045")
        self.m044.setText("M044")
        self.m050.setText("M050")
        self.m049.setText("M049")
        self.m044.setText("M044")
        self.m043.setText("M043")
        self.m042.setText("M042")
        self.m027.setText("M027")
        self.m028.setText("M028")
        self.m029.setText("M029")
        self.m037.setText("M037")
        self.m030.setText("M030")
        self.m038.setText("M038")
        self.m031.setText("M031")
        self.m036.setText("M036")
        self.m035.setText("M035")
        self.m032.setText("M032")
        self.m033.setText("M033")
        self.m034.setText("M034")
        self.m039.setText("M039")
        self.m040.setText("M040")
        self.m041.setText("M041")
        self.m004.setText("M004")
        self.m005.setText("M005")
        self.m003.setText("M003")
        self.m006.setText("M006")
        self.m010.setText("M010")
        self.m011.setText("M011")
        self.m012.setText("M012")
        self.m013.setText("M013")
        self.m014.setText("M014")
        self.m015.setText("M015")
        self.m016.setText("M016")
        self.m017.setText("M017")
        self.m018.setText("M018")
        self.m002.setText("M002")
        self.m001.setText("M001")
        self.m019.setText("M019")
        self.m009.setText("M009")
        self.m007.setText("M007")
        self.m008.setText("M008")
        self.m023.setText("M023")
        self.m021.setText("M021")
        self.m022.setText("M022")
        self.m025.setText("M025")
        self.m024.setText("M024")
        self.m026.setText("M026")
        self.m051.setText("M051")
        self.pushButton_t004.setText("T004")
        self.pushButton_t003.setText("T003")      
        self.pushButton_t005.setText("T005")
        self.pushButton_t002.setText("T002")
        self.pushButton_t001.setText("T001")
        self.d001.setText("D001")
        self.d002.setText("D002")
        self.d009.setText("D009")
        self.d008.setText("D008")
        self.d003.setText("D003")
        self.d004.setText("D004")
        self.d006.setText("D006")
        self.d011.setText("D011")
        self.d051.setText("D051")
        self.m020.setText("M020")
        self.e002.setText("E002")
        self.l002.setText("L002")
        self.l001.setText("L001")
        self.e001.setText("E001")
        self.l011.setText("L011")
        self.l009.setText("L009")
        self.l006.setText("L006")
        self.f001.setText("F001")
        self.f002.setText("F002")
        self.l007.setText("L007")
        self.l004.setText("L004")
        self.l005.setText("L005")
        self.i008.setText("I008")
        self.i009.setText("I009")
        self.l003.setText("L003")
        self.d005.setText("D005")
        self.i011.setText("I011")
        self.i012.setText("I012")
        self.r002.setText("R002")
        self.l010.setText("L010")
        self.d003.setText("D003")
        self.l008.setText("L008")
        self.d012.setText("D012")
        self.d016.setText("D016")
        self.d007.setText("D007")
        self.d014.setText("D014")
        self.d015.setText("D015")
        self.d010.setText("D010")
        self.r001.setText("R001")
        
        self.label_5.setText(str(self.Slider_5.value()))
        self.label_4.setText(str(self.Slider_4.value()))
        self.label_3.setText(str(self.Slider_3.value()))
        self.label_2.setText(str(self.Slider_2.value()))
        self.label_1.setText(str(self.Slider_1.value()))
        

        self.toolButton.setText("打开日志")
        self.toolButton_2.setText("保存日志")
        self.logButton.setText("生成日志")



class MyMainWindow(QMainWindow, Ui_MainWindow):
    def __init__(self, parent=None):
        super(MyMainWindow, self).__init__(parent)
        self.setupUi(self)

if __name__ == '__main__':
    app = QtWidgets.QApplication(sys.argv)
    myWin = MyMainWindow()
    myWin.show()
    sys.exit(app.exec_())
